# Generated by Django 4.2.1 on 2023-05-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='package',
            name='details',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
