# Generated by Django 4.2.1 on 2023-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_package_name_package_name_package_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
